### ISSUE TITLE
PRODUCTION-INSTALL.md is outdated

### ISSUE THREAD

**Issue by yuriiz** [dimagi/commcare-hq#13767]
Single server production installation instructions at PRODUCTION-INSTALL.md are highly outdated and contain several instructions that won't work and README.md is for development setup only and not for production.

Issues:
### Install dependencies
- Won't install kafka which seems to be required.
### Define a server configuration
1. Missing git submodule update
   fabfile.py imports fab which is symlink inside submodule, so without submodule it won't work.
2. "Next, edit fabfile.py to add a new task definition for your server:"
   Editing file like indicated will result in:

```
Traceback (most recent call last):
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/commcarehq/commcare-hq/fabfile.py", line 17, in myserver
    env.user = prompt("Username: ", default=env.user)
NameError: global name 'prompt' is not defined
```

and

```
Traceback (most recent call last):
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/commcarehq/commcare-hq/fabfile.py", line 20, in myserver
    _setup_path()
NameError: global name '_setup_path' is not defined
```

(`from fab.fabfile import *` does not import `_setup_path` or anything else starting with `_`)

But even after fixing it, fabfile.py will be still unusable as any command will fail with:

```
Traceback (most recent call last):
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/commcarehq/commcare-hq/fabfile.py", line 21, in myserver
    _setup_path()
  File "/home/commcarehq/commcare-hq/fab/fabfile.py", line 128, in _setup_path
    env.root = posixpath.join(env.home, 'www', env.environment)
  File "/home/commcarehq/local/lib/python2.7/site-packages/fabric/utils.py", line 213, in __getattr__
    raise AttributeError(key)
AttributeError: home
```
### Set up code checkouts, virtualenvs, and apache config

`fab myserver bootstrap` - there is no "bootstrap" command.
### Edit localsettings.py

Missing several settings when kept unchanged won't work:
SHARED_DRIVE_ROOT - required to be set
LOCAL_APPS - must have "kombu.transport.django"
DEBUG is True by default but should be turned off if service is exposed to public.
### Configure Supervisor

Does not mention where are /home/cchq/services come from.
As far as I understand must be created by some fabfile command but fabric does not work at all for reasons described above.
### Sync HQ with databases

env CCHQ_IS_FRESH_INSTALL=1 must be set during migrate
### Start HQ

Does not mention kafka has to be started.
Missing ./mange.py create_kafka_topics
Missing npm, bower installation and ./manage.py collectstatic
Missing nginx/apache configuration instructions.

**Comment by yuriiz** [comment]
Suggested changes: https://github.com/qedsoftware/commcare-hq/blob/ac24bc90add737179b7b2c0b2646531d45d69122/PRODUCTION-INSTALL.md

**Comment by czue** [comment]
@yuriiz would it be possible to pull request your suggested changes so we can see the diff easily? as you might have noted `PRODUCTION-INSTALL.md` has not been modified in over 3 years and as you have found, is wildly out of date.

everything you mentioned just seems like either stale/out of date issues that should be addressed or gaps in existing documentation that would be great to fill so it would be awesome if you have them updated to get them back in the docs.

apologies about the gaps here. as you may or may not know we now use the [ansible repo](https://github.com/dimagi/commcarehq-ansible) to manage all our production environments, and so haven't had much need for this file as the documentation is the ansible code itself.

**Comment by yuriiz** [comment]
Created pull request to this repository: https://github.com/dimagi/commcare-hq/pull/13783
