### ISSUE TITLE
Unable to validate the forms due to a server error. Please try again later.

### ISSUE THREAD

**Issue by AnasBhih** [dimagi/commcare-hq#21008]
After installing commcare-hq and building an application, i tried to publish my application,
But creating new application version is raising an error

Cannot Create Menus
Details: Unable to validate the forms due to a server error. Please try again later.

**Console**

less-1.7.3.min.js:13 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
r @ less-1.7.3.min.js:13
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/hqwebapp/less/bootstrap.debug.less generated in 685ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/font-awesome/less/font-awesome.less generated in 131ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/hqwebapp/less/font-commcare.less generated in 11ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/hqwebapp/less/style.debug.less generated in 128ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/app_manager/less/font-workflow.less generated in 9ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/app_manager/less/app_manager.debug.less generated in 68ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/app_manager/less/preview_app.debug.less generated in 33ms
less-1.7.3.min.js:13 less: less has finished. css generated in 1066ms
logging.js:91 DEBUG | Google Analytics    
logging.js:71 Failed to initialize because apiId was not provided
logging.js:91 DEBUG | Kissmetrics    
logging.js:71 Failed to initialize because apiId was not provided
logging.js:91 DEBUG | Hubspot    
logging.js:71 Failed to initialize because apiId was not provided
logging.js:91 DEBUG | Drift    
logging.js:71 Failed to initialize because apiId was not provided
logging.js:91 DEBUG | Appcues    
logging.js:71 Failed to initialize because apiId was not provided
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/hqwebapp/less/bootstrap.debug.less generated in 869ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/font-awesome/less/font-awesome.less generated in 136ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/hqwebapp/less/font-commcare.less generated in 15ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/hqwebapp/less/style.debug.less generated in 122ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/cloudcare/less/font-formplayer.less generated in 25ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/cloudcare/less/formplayer-common.debug.less generated in 66ms
less-1.7.3.min.js:13 less: css for http://165.16.67.156:8000/static/preview_app/less/preview_app.debug.less generated in 61ms
less-1.7.3.min.js:13 less: less has finished. css generated in 1294ms
logging.js:91 DEBUG | Google Analytics    
logging.js:71 Failed to initialize because apiId was not provided
logging.js:91 DEBUG | Kissmetrics    
logging.js:71 Failed to initialize because apiId was not provided
logging.js:91 DEBUG | Hubspot    
logging.js:71 Failed to initialize because apiId was not provided
logging.js:91 DEBUG | Drift    
logging.js:71 Failed to initialize because apiId was not provided
logging.js:91 DEBUG | Appcues    
logging.js:71 Failed to initialize because apiId was not provided
middleware.js:19 User navigated to singleApp
localhost:8010/delete_application_dbs:1 Failed to load resource: net::ERR_CONNECTION_REFUSED

**Server**

```
2018-06-23 20:19:18,062 INFO "GET /a/firstproject/apps/view/ce10d51a6470029490265ce8f79ac915/current_version/ HTTP/1.1" 200 71
2018-06-23 20:19:18,399 ERROR Notify Exception: Error calling Formplayer form validation endpoint
Traceback (most recent call last):
  File "/projects/commcare-hq/corehq/apps/formplayer_api/form_validation.py", line 47, in validate_form
    headers={'Content-Type': 'application/xml'}
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8010): Max retries exceeded with url: /validate_form (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f5ce0bd5290>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-06-23 20:19:18,775 ERROR Notify Exception: Error calling Formplayer form validation endpoint
Traceback (most recent call last):
  File "/projects/commcare-hq/corehq/apps/formplayer_api/form_validation.py", line 47, in validate_form
    headers={'Content-Type': 'application/xml'}
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8010): Max retries exceeded with url: /validate_form (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f5ce0a70910>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-06-23 20:19:18,801 ERROR Notify Exception: Error calling Formplayer form validation endpoint
Traceback (most recent call last):
  File "/projects/commcare-hq/corehq/apps/formplayer_api/form_validation.py", line 47, in validate_form
    headers={'Content-Type': 'application/xml'}
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/root/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8010): Max retries exceeded with url: /validate_form (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f5ce0a70d10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-06-23 20:19:18,886 INFO "POST /a/firstproject/apps/save/ce10d51a6470029490265ce8f79ac915/ HTTP/1.1" 200 673
2018-06-23 20:19:20,269 INFO "GET /a/firstproject/apps/view/ce10d51a6470029490265ce8f79ac915/current_version/ HTTP/1.1" 200 71

```

**Comment by snopoke** [comment]
This occurs when you don't have formplayer running: https://github.com/dimagi/commcare-hq/#formplayer
