### ISSUE TITLE
Read the docs builds are broken

### ISSUE THREAD

**Issue by emord** [dimagi/commcare-hq#21347]
First build fail happened after openpyxl upgrade.

```
Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 26, in <module>
    django.setup()
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/checkouts/latest/manage.py", line 51, in _setup_once
    _setup_once.setup(*args, **kw)
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/checkouts/latest/corehq/apps/smsbillables/models.py", line 24, in <module>
    from corehq.messaging.smsbackends.test.models import SQLTestSMSBackend
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/checkouts/latest/corehq/messaging/smsbackends/test/models.py", line 6, in <module>
    from corehq.apps.sms.forms import BackendForm
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/checkouts/latest/corehq/apps/sms/forms.py", line 21, in <module>
    from corehq.apps.reminders.forms import validate_time
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/checkouts/latest/corehq/apps/reminders/forms.py", line 25, in <module>
    from corehq.apps.locations.util import get_locations_from_ids
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/checkouts/latest/corehq/apps/locations/util.py", line 21, in <module>
    from couchexport.writers import Excel2007ExportWriter
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/checkouts/latest/corehq/ex-submodules/couchexport/writers.py", line 15, in <module>
    import openpyxl
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/openpyxl/__init__.py", line 26, in <module>
    from openpyxl.compat.numbers import NUMPY, PANDAS
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/openpyxl/compat/__init__.py", line 5, in <module>
    from .strings import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/openpyxl/compat/strings.py", line 10, in <module>
    from .numbers import NUMERIC_TYPES
  File "/home/docs/checkouts/readthedocs.org/user_builds/commcare-hq/envs/latest/local/lib/python2.7/site-packages/openpyxl/compat/numbers.py", line 28, in <module>
    import pandas
  File "/usr/lib/python2.7/dist-packages/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:38262)
ValueError: numpy.dtype has the wrong size, try recompiling
```

first failure: https://readthedocs.org/projects/commcare-hq/builds/7477985/
PR that broke: https://github.com/dimagi/commcare-hq/pull/21159

**Comment by emord** [comment]
Just resolved this, by changing our read the docs configuration to not use system installed packages.

This showed up because pandas is installed on the system, and openpyxl [tries to import pandas if possible](https://bitbucket.org/openpyxl/openpyxl/src/5983d4ba5c18b85171185e8b1ca136876ec52864/openpyxl/compat/numbers.py?at=default&fileviewer=file-view-default#numbers.py-27:31)

Might have also been able to solve this by mocking pandas https://github.com/dimagi/commcare-hq/blob/master/docs/conf.py#L28-L33 but not doing that for now
