### ISSUE TITLE
Error during installing commcare 

### ISSUE THREAD

**Issue by omiltoro** [dimagi/commcare-hq#5315]
I get the following error when i run manage.py validate.

All dependencies have been installed

(commcare-hq)patrick@patrick-vbox:~/commcare-hq$ ./manage.py validate
Traceback (most recent call last):
  File "./manage.py", line 65, in <module>
    execute_from_command_line(sys.argv)
  File "/home/patrick/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/home/patrick/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/patrick/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/home/patrick/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/home/patrick/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/patrick/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._configure_logging()
  File "/home/patrick/.virtualenvs/commcare-hq/local/lib/python2.7/site-packages/django/conf/__init__.py", line 84, in _configure_logging
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 777, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 575, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'couchlog': Cannot resolve 'couchlog.handlers.CouchHandler': No module named couchlog
(commcare-hq)patrick@patrick-vbox:~/commcare-hq$

**Comment by czue** [comment]
have you updated all submodules as well? 

`git submodule update --init --recursive`

if the error is just with couchlog you can also just remove/override that log handler in settings/localsettings.

**Comment by omiltoro** [comment]
Hi czue,

Thank you. I think that was the issue. 

Thanks
