### ISSUE TITLE
Tests failing locally

### ISSUE THREAD

**Issue by millerdev** [dimagi/commcare-hq#7640]
I'm seeing test failures on master. First I went through this routine to make sure I was up to date:

``` sh
$ pull-code
$ find . -name '*.pyc' -delete
$ pip install -r requirements/requirements.txt
$ pip install -r requirements/dev-requirements.txt
$ ./manage.py syncdb
$ ./manage.py migrate
```

Worked around various errors in that process, but eventually got the issues sorted.

Here's an example of a failing test:

```
$ ./manage.py test auditcare --failfast
...
======================================================================
ERROR: testModelEventChanges (auditcare.tests.modelevents.ModelEventTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./submodules/auditcare-src/auditcare/tests/modelevents.py", line 18, in setUp
    self._createUser()
  File "./submodules/auditcare-src/auditcare/tests/modelevents.py", line 37, in _createUser
    self.assertEqual(model_count+1, model_count2)
AssertionError: 1 != 0
```

**Comment by benrudolph** [comment]
one thing that comes to mind is that the User model is not included in the settings: https://github.com/dimagi/commcare-hq/blob/dropbox/settings.py#L675. (i tried to change that though with no luck)

**Comment by benrudolph** [comment]
sorry that does fix it! i don't know what i was doing. just add this: `'django.contrib.auth.models.User'` to that array. though i don't know what that model isn't in the AuditCare settings to begin with

**Comment by millerdev** [comment]
Is that something I should do locally, or are you making a PR to fix it?

**Comment by millerdev** [comment]
Why are these tests not failing on prod if they're failing locally for me?

**Comment by benrudolph** [comment]
I didn't do anything cause I don't run those tests very often. Travis uses
a different localsettings located '.travis/localsettings.py'

**Comment by millerdev** [comment]
When I opened this issue the other day I knew there were other errors, but didn't have them handy. Here are other failures I get:
```
======================================================================
ERROR: test (corehq.apps.receiverwrapper.tests.test_app_id.TestAppId)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/receiverwrapper/tests/test_app_id.py", line 33, in test
    self._test_app_version(self.domain, form, build)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/receiverwrapper/tests/test_app_id.py", line 53, in _test_app_version
    self.assertEqual(get_version_from_build_id(domain, form.build_id),
  File "/Users/dimagi/code/commcare-hq/corehq/apps/receiverwrapper/util.py", line 62, in get_version_from_build_id
    cache_value = json.dumps(_get_version_from_build_id(domain, build_id))
  File "/Users/dimagi/code/commcare-hq/corehq/apps/receiverwrapper/util.py", line 69, in _get_version_from_build_id
    build = ApplicationBase.get(build_id)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/schema/base.py", line 169, in get
    return db.get(docid, rev=rev, wrapper=cls.wrap)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 390, in open_doc
    return wrapper(doc)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3195, in wrap
    self.build_spec = get_default_build_spec(self.application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/utils.py", line 18, in get_default_build_spec
    return CommCareBuildConfig.fetch().get_default(application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 285, in inner
    return helper(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 85, in __call__
    content = self.fn(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 218, in fetch
    return cls.bootstrap()
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 205, in bootstrap
    config.save()
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/schema/base.py", line 134, in save
    db.save_doc(doc, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 515, in save_doc
    **params).json_body
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/restkit/resource.py", line 153, in put
    headers=headers, params_dict=params_dict, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/resource.py", line 133, in request
    response=e.response)
ResourceConflict: Document update conflict.

======================================================================
ERROR: testBuildImportedApp (corehq.apps.app_manager.tests.test_app_manager.AppManagerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/mock.py", line 1224, in patched
    return func(*args, **keywargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_app_manager.py", line 150, in testBuildImportedApp
    app = import_app(self._yesno_source, self.domain)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 4671, in import_app
    app = cls.from_source(source, domain)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3058, in from_source
    app = cls.wrap(source)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3716, in wrap
    self = super(Application, cls).wrap(data)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3195, in wrap
    self.build_spec = get_default_build_spec(self.application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/utils.py", line 18, in get_default_build_spec
    return CommCareBuildConfig.fetch().get_default(application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 285, in inner
    return helper(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 85, in __call__
    content = self.fn(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 218, in fetch
    return cls.bootstrap()
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 205, in bootstrap
    config.save()
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/schema/base.py", line 134, in save
    db.save_doc(doc, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 515, in save_doc
    **params).json_body
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/restkit/resource.py", line 153, in put
    headers=headers, params_dict=params_dict, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/resource.py", line 133, in request
    response=e.response)
ResourceConflict: Document update conflict.

======================================================================
ERROR: testImportApp (corehq.apps.app_manager.tests.test_app_manager.AppManagerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/mock.py", line 1224, in patched
    return func(*args, **keywargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_app_manager.py", line 85, in testImportApp
    new_app = import_app(self.app.id, self.domain)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 4651, in import_app
    source = get_app(None, app_id)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 4637, in get_app
    app = cls.wrap(app)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3716, in wrap
    self = super(Application, cls).wrap(data)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3195, in wrap
    self.build_spec = get_default_build_spec(self.application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/utils.py", line 18, in get_default_build_spec
    return CommCareBuildConfig.fetch().get_default(application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 285, in inner
    return helper(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 85, in __call__
    content = self.fn(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 218, in fetch
    return cls.bootstrap()
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 205, in bootstrap
    config.save()
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/schema/base.py", line 134, in save
    db.save_doc(doc, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 515, in save_doc
    **params).json_body
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/restkit/resource.py", line 153, in put
    headers=headers, params_dict=params_dict, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/resource.py", line 133, in request
    response=e.response)
ResourceConflict: Document update conflict.

======================================================================
ERROR: test_app_base (corehq.apps.app_manager.tests.test_brief_view.BriefViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_brief_view.py", line 30, in test_app_base
    apps = get_apps_in_domain(self.domain)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 4572, in get_apps_in_domain
    wrapped_apps = [get_correct_app_class(row['doc']).wrap(row['doc']) for row in view_results]
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3195, in wrap
    self.build_spec = get_default_build_spec(self.application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/utils.py", line 18, in get_default_build_spec
    return CommCareBuildConfig.fetch().get_default(application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 285, in inner
    return helper(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 85, in __call__
    content = self.fn(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 218, in fetch
    return cls.bootstrap()
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 205, in bootstrap
    config.save()
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/schema/base.py", line 134, in save
    db.save_doc(doc, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 515, in save_doc
    **params).json_body
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/restkit/resource.py", line 153, in put
    headers=headers, params_dict=params_dict, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/resource.py", line 133, in request
    response=e.response)
ResourceConflict: Document update conflict.

======================================================================
ERROR: test_domain (corehq.apps.app_manager.tests.test_brief_view.BriefViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_brief_view.py", line 26, in test_domain
    apps = self.project.applications()
  File "/Users/dimagi/code/commcare-hq/corehq/apps/domain/models.py", line 477, in applications
    endkey=[self.name, {}]).all()
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 1014, in all
    return list(self.iterator())
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 977, in iterator
    yield wrapper(row)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 958, in row_wrapper
    return schema_wrapper(data)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3195, in wrap
    self.build_spec = get_default_build_spec(self.application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/utils.py", line 18, in get_default_build_spec
    return CommCareBuildConfig.fetch().get_default(application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 285, in inner
    return helper(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 85, in __call__
    content = self.fn(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 218, in fetch
    return cls.bootstrap()
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 205, in bootstrap
    config.save()
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/schema/base.py", line 134, in save
    db.save_doc(doc, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 515, in save_doc
    **params).json_body
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/restkit/resource.py", line 153, in put
    headers=headers, params_dict=params_dict, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/resource.py", line 133, in request
    response=e.response)
ResourceConflict: Document update conflict.

======================================================================
ERROR: test (corehq.apps.app_manager.tests.test_form_versioning.FormVersioningTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/mock.py", line 1224, in patched
    return func(*args, **keywargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_form_versioning.py", line 89, in test
    xxx_app = import_app(app.export_json(dump_json=False), domain)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 4671, in import_app
    app = cls.from_source(source, domain)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3058, in from_source
    app = cls.wrap(source)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3716, in wrap
    self = super(Application, cls).wrap(data)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3195, in wrap
    self.build_spec = get_default_build_spec(self.application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/utils.py", line 18, in get_default_build_spec
    return CommCareBuildConfig.fetch().get_default(application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 285, in inner
    return helper(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 85, in __call__
    content = self.fn(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 218, in fetch
    return cls.bootstrap()
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 205, in bootstrap
    config.save()
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/schema/base.py", line 134, in save
    db.save_doc(doc, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 515, in save_doc
    **params).json_body
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/restkit/resource.py", line 153, in put
    headers=headers, params_dict=params_dict, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/resource.py", line 133, in request
    response=e.response)
ResourceConflict: Document update conflict.

======================================================================
ERROR: test_advanced_module (corehq.apps.app_manager.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 173, in test_advanced_module
    'module_id': module.id,
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 111, in _test_status_codes
    response = self.client.get(reverse(name, kwargs=kwargs), follow=False)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/domain/decorators.py", line 80, in _inner
    return view_func(req, domain_name, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/views.py", line 1169, in view_module
    return view_generic(request, domain, app_id, module_id)
  File "./submodules/dimagi-utils-src/dimagi/utils/couch/resource_conflict.py", line 27, in new_fn
    raise RetryResourceError(fn, n)
RetryResourceError: 'Tried function `view_generic` 3 time(s) and conflicted every time.'

======================================================================
ERROR: test_basic_app (corehq.apps.app_manager.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 132, in test_basic_app
    ], kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 111, in _test_status_codes
    response = self.client.get(reverse(name, kwargs=kwargs), follow=False)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/domain/decorators.py", line 80, in _inner
    return view_func(req, domain_name, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/views.py", line 1182, in view_app
    return view_generic(request, domain, app_id)
  File "./submodules/dimagi-utils-src/dimagi/utils/couch/resource_conflict.py", line 27, in new_fn
    raise RetryResourceError(fn, n)
RetryResourceError: 'Tried function `view_generic` 3 time(s) and conflicted every time.'

======================================================================
ERROR: test_careplan_module (corehq.apps.app_manager.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 195, in test_careplan_module
    'module_id': module.id,
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 111, in _test_status_codes
    response = self.client.get(reverse(name, kwargs=kwargs), follow=False)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/domain/decorators.py", line 80, in _inner
    return view_func(req, domain_name, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/views.py", line 1169, in view_module
    return view_generic(request, domain, app_id, module_id)
  File "./submodules/dimagi-utils-src/dimagi/utils/couch/resource_conflict.py", line 27, in new_fn
    raise RetryResourceError(fn, n)
RetryResourceError: 'Tried function `view_generic` 3 time(s) and conflicted every time.'

======================================================================
ERROR: test_edit_commcare_profile (corehq.apps.app_manager.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 88, in test_edit_commcare_profile
    content = json.loads(response.content)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

======================================================================
ERROR: test_report_module (corehq.apps.app_manager.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 182, in test_report_module
    'module_id': module.id,
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 111, in _test_status_codes
    response = self.client.get(reverse(name, kwargs=kwargs), follow=False)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/domain/decorators.py", line 80, in _inner
    return view_func(req, domain_name, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/views.py", line 1169, in view_module
    return view_generic(request, domain, app_id, module_id)
  File "./submodules/dimagi-utils-src/dimagi/utils/couch/resource_conflict.py", line 27, in new_fn
    raise RetryResourceError(fn, n)
RetryResourceError: 'Tried function `view_generic` 3 time(s) and conflicted every time.'

======================================================================
ERROR: test_user_registration (corehq.apps.app_manager.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 164, in test_user_registration
    'app_id': self.app.id,
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 111, in _test_status_codes
    response = self.client.get(reverse(name, kwargs=kwargs), follow=False)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/domain/decorators.py", line 80, in _inner
    return view_func(req, domain_name, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/users/decorators.py", line 21, in _inner
    return view_func(request, domain, *args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/views.py", line 1157, in view_user_registration
    return view_generic(request, domain, app_id, is_user_registration=True)
  File "./submodules/dimagi-utils-src/dimagi/utils/couch/resource_conflict.py", line 27, in new_fn
    raise RetryResourceError(fn, n)
RetryResourceError: 'Tried function `view_generic` 3 time(s) and conflicted every time.'

======================================================================
ERROR: test_updating_out_of_date_report (corehq.apps.userreports.tests.test_report_builder.ReportBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/userreports/tests/test_report_builder.py", line 47, in test_updating_out_of_date_report
    'columns': '[]',
  File "/Users/dimagi/code/commcare-hq/corehq/apps/userreports/reports/builder/forms.py", line 423, in __init__
    self.app = Application.get(app_id)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/schema/base.py", line 169, in get
    return db.get(docid, rev=rev, wrapper=cls.wrap)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 390, in open_doc
    return wrapper(doc)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3716, in wrap
    self = super(Application, cls).wrap(data)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/models.py", line 3195, in wrap
    self.build_spec = get_default_build_spec(self.application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/utils.py", line 18, in get_default_build_spec
    return CommCareBuildConfig.fetch().get_default(application_version)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 285, in inner
    return helper(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/util/quickcache.py", line 85, in __call__
    content = self.fn(*args, **kwargs)
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 218, in fetch
    return cls.bootstrap()
  File "/Users/dimagi/code/commcare-hq/corehq/apps/builds/models.py", line 205, in bootstrap
    config.save()
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/schema/base.py", line 134, in save
    db.save_doc(doc, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/client.py", line 515, in save_doc
    **params).json_body
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/restkit/resource.py", line 153, in put
    headers=headers, params_dict=params_dict, **params)
  File "/Users/dimagi/code/virtualenvs/hq/lib/python2.7/site-packages/couchdbkit/resource.py", line 133, in request
    response=e.response)
ResourceConflict: Document update conflict.

======================================================================
FAIL: test_should_sync_locations_change_location_type (corehq.apps.locations.tests.test_location_fixtures.LocationFixturesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/locations/tests/test_location_fixtures.py", line 79, in test_should_sync_locations_change_location_type
    self.assertFalse(should_sync_locations(SyncLog(date=yesterday), location_db, self.user))
AssertionError: True is not False

======================================================================
FAIL: test_hours (corehq.apps.app_manager.tests.test_success_message.SuccessMessageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/app_manager/tests/test_success_message.py", line 88, in test_hours
    ).format(self=self), nature=ResponseNature.SUBMIT_SUCCESS)
AssertionError: '<OpenRosaResponse xmlns="http://openrosa.org/http/response"><message nature="submit_error">Document update conflict.</message></OpenRosaResponse>' != '<OpenRosaResponse xmlns="http://openrosa.org/http/response"><message nature="submit_success">Thanks Danny (Danny Roberts)! You have submitted 1 forms today and 1 forms since Monday.</message></OpenRosaResponse>'

======================================================================
FAIL: test_patches (corehq.apps.userreports.tests.test_multi_db.UCRMultiDBTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dimagi/code/commcare-hq/corehq/apps/userreports/tests/test_multi_db.py", line 115, in test_patches
    self.assertEqual(settings.SQL_REPORTING_DATABASE_URL, str(self.ds1_adapter.engine.url))
AssertionError: 'postgresql+psycopg2://postgres:******@localhost:5432/test_commcarehq' != 'postgresql+psycopg2://postgres:%2A%2A%2A%2A%2A%2A@localhost:5432/test_commcarehq'

----------------------------------------------------------------------
```

**Comment by benrudolph** [comment]
The `Document Conflict Errors` are weird haven't seen those ever. do you get those when you run the whole test suite at once? Are you just running `./manage test`?

**Comment by millerdev** [comment]
Yes, these are all errors I got from just running `./manage.py test`

Does no one run the entire test suite locally anymore?

**Comment by benrudolph** [comment]
i did that once when i first arrived and someone told me no one does that haha

**Comment by czue** [comment]
@millerdev guessing this can be closed, yeah?

**Comment by millerdev** [comment]
Sure
