### ISSUE TITLE
Can deploy projects

### ISSUE THREAD

**Issue by freemanpolys** [dimagi/commcare-hq#9243]
Hi,

We have installed two versions off commcare the 1.6 and 2.0.
We can't deploy project on both off them.

find logs below : 

ERROR 2015-11-23 18:14:08,086 base 22858 140059034912512 Internal Server Error: /a/recensement/apps/save/3796262ded9f5c377930313def7387c2/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/home/cchq/commcare-hq/corehq/apps/app_manager/decorators.py", line 49, in _no_conflict
    return f(*args, **kwargs)
  File "/home/cchq/commcare-hq/corehq/apps/domain/decorators.py", line 77, in _inner
    return view_func(req, domain_name, *args, **kwargs)
  File "/home/cchq/commcare-hq/corehq/apps/users/decorators.py", line 21, in _inner
    return view_func(request, domain, *args, **kwargs)
  File "/home/cchq/commcare-hq/corehq/apps/app_manager/views/releases.py", line 145, in save_copy
    errors = app.validate_app()
  File "/home/cchq/commcare-hq/corehq/apps/app_manager/models.py", line 4963, in validate_app
    errors = super(Application, self).validate_app()
  File "/home/cchq/commcare-hq/corehq/apps/app_manager/models.py", line 4113, in validate_app
    self.validate_jar_path()
  File "/home/cchq/commcare-hq/corehq/apps/app_manager/models.py", line 4040, in validate_jar_path
    build = self.get_build()
  File "/home/cchq/commcare-hq/corehq/apps/app_manager/models.py", line 3901, in get_build
    return self.build_spec.get_build()
  File "/home/cchq/commcare-hq/corehq/apps/builds/models.py", line 141, in get_build
    return CommCareBuild.get_build(self.version, latest=True)
  File "/home/cchq/commcare-hq/corehq/apps/builds/models.py", line 125, in get_build
    latest=latest
KeyError: "Can't find build 2.0.0/latest. For instructions on how to add it, see https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/builds/README.md"

Regards,

**Comment by czue** [comment]
@freemanpolys I think the error message is linking you to the instructions on how to fix this?

**Comment by freemanpolys** [comment]
Ok @czue thanks for the response. I'll try to follow this instructions an let you know.
Tell me, with this install, will I have all the features ?

**Comment by czue** [comment]
This is the same code that we use on our production servers so all the features there should be available/able to be made available here.
